const mongoose = require("mongoose");
const ticketSchema = new mongoose.Schema({
  ticketNumber: { type: String },
  busNumber: { type: String, required: true },
  routeNumber: { type: String, default: "" },
  machineId: { type: String, default: "" },
  batch_no: { type: String },
  conductorId: { type: String },
  conductorName: { type: String },
  boardingStop: { type: String, required: true },
  destinationStop: { type: String, required: true },
  price: { type: Number, required: true },
  paymentMode: { type: String, required: true },
  selectedPass: { type: String, default: "None" },
  adultCount: { type: Number, default: 0 },
  childCount: { type: Number, default: 0 },
  basePrice: { type: Number, default: 0 },
  passCounts: { type: Object, default: {} },
  passNumbers: { type: Object, default: {} },
  luggageCount: { type: Number, default: 0 },
  luggageAmount: { type: Number, default: 0 },
  dateTime: { type: Date, default: Date.now },
  date: { type: String },
  time: { type: String },
  status: { type: String, default: "confirmed" },
});
module.exports = mongoose.model("Ticket", ticketSchema, "Ticket");